### ISSUE TITLE
Yeah

### ISSUE THREAD

**Issue by 74opt** [ruwey/web-dev#1]
So true bestie 

did you know that aramie is just using google drive instead of making a repo for web dev shit 

it's wild

**Comment by ruwey** [comment]
@AwareErmine  this makes me very sad

**Comment by ruwey** [comment]
devistated

**Comment by AwareErmine** [comment]
well
annoying password to clone 3 files or awesome cool gmail password for *both* gc and the code?? Quick easy download as zip??

**Comment by ruwey** [comment]
if only you could have an ssh key on a security key and just plug it in...

**Comment by AwareErmine** [comment]
if only

**Comment by ruwey** [comment]
resolved: wont fix
